[package]
name = "jeryu-obs"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dev-dependencies]
redlinedb = { git = "http://127.0.0.1:8787/git/jeryu/redline-core.git", tag = "redline-core-v4.1.0-jain.4" }
tempfile.workspace = true
